export const LOCAL_STORAGE_KEY = 'timr-app.intervals';
export const CONNECTED = 'CONNECTED';

export const INTERVAL_ADD = 'INTERVAL_ADD';
export const INTERVAL_UPDATE = 'INTERVAL_UPDATE';
export const INTERVAL_COMPLETE = 'INTERVAL_COMPLETE';
export const INTERVAL_REMOVE = 'INTERVAL_REMOVE';
export const INTERVALS_FETCHED = 'INTERVALS_FETCHED';

export const STARTED_WORKING = 'STARTED_WORKING';
export const STOPPED_WORKING = 'STOPPED_WORKING';

export const TOGGLE_DISPLAY_NOTIFICATIONS = 'TOGGLE_DISPLAY_NOTIFICATIONS';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
