export const testIds = {
  appInit: 'app-init',
  loginForm: 'login-form',
  workButton: 'work-button',
  userMenuToggle: 'user-menu-toggle',
  userMenu: 'user-menu',
  loadingIntervals: 'loading-intervals-container',
  currentIntervals: 'current-intervals-list',
  interval: 'interval-item',
  intervalFromInput: 'interval-from-input',
  intervalEndInput: 'interval-end-input',
  intervalNoteInput: 'interval-note-input',
  intervalNotWorkCheckbox: 'interval-not-work-checkbox',
  weekStatItem: 'week-stats-item',
  removeIntervalBtn: 'remove-interval',
  regPrevWorkBtn: 'register-previous-work-button',
  savePrevWorkBtn: 'add-one-interval-save-btn',
  cancelPrevWorkBtn: 'add-one-interval-cancel-btn',
  addPrevIntervalForm: 'add-previous-interval-form',
  prevWeekBtn: 'prev-week-btn',
  nextWeekBtn: 'next-week-btn',
};
export const animationDuration = 500;
